version: "3.3"

networks:
  inner:
    driver: bridge

services:
  bot:
    build: .
    restart: always
    networks:
      - inner
    depends_on:
      - mongo

  mongo:
    image: "mongo"
    restart: always
    ports:
      - 27017:27017
    networks:
      - inner
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
